### ISSUE TITLE
Wrong partition number used in mksdcard

### ISSUE THREAD

**Issue by sfo** [MIPS/CI20_android#1]
There is an issue in the mksdcard script. It is assumed, that the first partition is named '1', e.g. at line 81 of the script:

`sudo mkfs.ext3 -L "CI20_Android" ${device}1`

But SD cards are named mmcblk0 with a partition counter of p1, p2, ...
So the script will fail to access partition mmcblk01, which has to be mmcblkp1 instead.

**Comment by ZubairLK** [comment]
I have a feeling that script is meant to run on a x86 Debian host machine where the sd card appears like /dev/sdc1 etc etc.

This depends on the host system I guess. What are you running this on?

**Comment by sfo** [comment]
I'm building on Ubuntu 14.04.1 LTS x86_64

**Comment by ZubairLK** [comment]
Interesting. 
My ubuntu 14 shows the sd card as /dev/sdc1 etc.
I use a usb sd card writer.

**Comment by sfo** [comment]
I've got a ThinkPad T420 with internal SD Card reader.
Just tested: When I use a usb sd card adapter, it gets mounted as /dev/sdbX

**Comment by chrisdearman** [comment]
Thanks for this change
